name: food_delivery_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.4.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_slidable: ^3.0.0
  flutter_slidable_panel: ^1.1.1
  flutter_advanced_drawer: ^1.3.5
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  google_sign_in: ^6.1.4
  image_picker: ^1.0.0
  permission_handler: ^10.4.2
  get_storage: ^2.1.1
  shimmer: ^3.0.0
  modal_progress_hud_nsn: ^0.4.0
  image_cropper: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^2.0.0


flutter:

  fonts:
    - family: SF Pro
      fonts:
        - asset:  assets/fonts/SF-Pro-Rounded-Medium.otf


  uses-material-design: true
  assets: 
    - assets/images/
    - assets/icons/

